name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**'

jobs:
  terraform:
    name: Terraform Infrastructure Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.x

      - name: Configure Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/terraform
        env:
          TF_VAR_database_url: ${{ secrets.DATABASE_URL }}
          TF_VAR_db_admin_user: ${{ secrets.DB_ADMIN_USER }}
          TF_VAR_db_admin_password: ${{ secrets.DB_ADMIN_PASSWORD }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
        run: terraform plan -out=tfplan -no-color
        continue-on-error: false

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan
        continue-on-error: false

      - name: Upload Terraform Plan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/tfplan
          retention-days: 7

